services:
  postgres:
    image: postgres:16
    container_name: usos_postgres
    environment:
      POSTGRES_USER: usos
      POSTGRES_PASSWORD: usos_password
      POSTGRES_DB: usos_dev
    ports:
      - "5432:5432"
    volumes:
      - usos_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: usos_redis
    ports:
      - "6379:6379"

volumes:
  usos_pgdata:
